apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  POSTGRES_USER: cm9vdA==
  POSTGRES_PASSWORD: cm9vdA==
  DATABASE_URL: cG9zdGdyZXNxbDovL3Jvb3Q6cm9vdEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvbm9kZS1hcGk/c2NoZW1hPXB1YmxpYw==