name: Deploy Client

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build the Client docker image
        run: docker build -t dockergl98/react-client-ts -f ./client/Dockerfile ./client
      - name: Push the Client docker image
        run: docker push dockergl98/react-client-ts
