name: Api Test cases

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing API
        run: cd api && npm install && npm run test
