name: Client Test cases

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing Client
        run: cd client && npm install && npm run test -- --watchAll=false
